.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. MintCoin_qt test_MintCoin_qt
clean: FORCE
	$(MAKE) -C .. MintCoin_qt_clean test_MintCoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_MintCoin_qt_check
MintCoin-qt MintCoin-qt.exe: FORCE
	 $(MAKE) -C .. MintCoin_qt
